### ISSUE TITLE
링크를 가르칠 수 있음

### ISSUE THREAD

**Issue by siy-uuu** [boranloves/shii#1]
https가 포함된 링크만 거르도록 되어있어 발생하는 문제로 보임.

**Comment by boranloves** [comment]
확인이 완료 되었으며, 현재 수정 중 입니다.
감사합니당

**Comment by boranloves** [comment]
모듈 수정이 완료 되었습니다! 다시한번 감사 드립니당

**Comment by siy-uuu** [comment]
discord.com/invite/

**Comment by boranloves** [comment]
확인이 완료 되었습니다..
중간고사 때문에 3일 정도만 더 기다려주시면 감사하겠습니다.
죄송합니다....

**Comment by boranloves** [comment]
오늘자(2024.5.9) 시이 v3.7.3 업데이트로 discord.com도 필터링하도록 되었습니다. 감사합니다!
